# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none
variables:
  folder: scr/
resources:
  repositories:
    - repository: mygitrepo
      type: github
      endpoint: SSH-TECH
      name: SSH-TECH/pipelines-java
pool:
  vmImage: ubuntu-latest

steps:
- checkout: mygitrepo
- task: Maven@3
  displayName: Build a java project
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    goals: 'package'


- task: CopyFiles@2
  displayName: copy package to artifact staging directory
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/target/*.?(war|jar)'
    TargetFolder: $(Build.ArtifactStagingDirectory)
- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop
